name: Evolve Devnet ANT Registry

on:
  push:
    branches:
      - main

jobs:
  # TODO: add unit tests using bused
  evolve:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn evolve
        env:
          WALLET: ${{ secrets.WALLET }}
          REGISTRY_ID: ${{ secrets.REGISTRY_ID }}
